#
# This source file is part of the NutriSight project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Beta Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      contents: read
      actions: read
      security-events: write
    secrets: inherit
  # iosapptestflightdeployment:
  #   name: iOS App TestFlight Deployment
  #   needs: buildandtest
  #   uses: SchmiedmayerLab/.github/.github/workflows/xcode-deploy.yml@v0.2
  #   concurrency:
  #     group: appstoreconnect
  #   permissions:
  #     contents: read
  #   with:
  #     runs_on_labels: '["macOS", "self-hosted"]'
  #     setup_signing: true
  #     command: fastlane beta
  #     environment: beta
  #   secrets: inherit
