#
# This source file is part of the NutriSight project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: SchmiedmayerLab/.github/.github/workflows/reuse.yml@v0.2.4
  swiftlint:
    name: SwiftLint
    uses: SchmiedmayerLab/.github/.github/workflows/swiftlint.yml@v0.2.4
  periphery:
    name: Periphery
    uses: SchmiedmayerLab/.github/.github/workflows/periphery.yml@v0.2.4
  # Disabled until https://github.com/github/codeql-action/issues/3978 is addressed.
  # codeql:
  #   name: CodeQL
  #   uses: SchmiedmayerLab/.github/.github/workflows/xcodebuild.yml@v0.2.4
  #   with:
  #     codeql: true
  #     scheme: NutriSight
  #   permissions:
  #     contents: read
  #     security-events: write
  buildandtest:
    name: Build and Test
    uses: SchmiedmayerLab/.github/.github/workflows/xcodebuild.yml@v0.2.4
    with:
      scheme: NutriSight
      resultBundle: NutriSight.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report / Merge and Upload Coverage
    needs: [buildandtest]
    runs-on: macos-26
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 26.0.1
      - name: Download coverage result
        uses: actions/download-artifact@v8
        with:
          name: NutriSight.xcresult
          path: NutriSight.xcresult
      - name: Convert coverage result
        uses: schmiedmayerlab/xccov2lcov@v1
        with:
          xcresult: NutriSight.xcresult
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: true
          files: info.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
