#
# This source file is part of the NutriSight project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: SchmiedmayerLab/.github/.github/workflows/reuse.yml@v0.2.4
  swiftlint:
    name: SwiftLint
    uses: SchmiedmayerLab/.github/.github/workflows/swiftlint.yml@v0.2.4
  periphery:
    name: Periphery
    uses: SchmiedmayerLab/.github/.github/workflows/periphery.yml@v0.2.4
  # Disabled until https://github.com/github/codeql-action/issues/3978 is addressed.
  # codeql:
  #   name: CodeQL
  #   uses: SchmiedmayerLab/.github/.github/workflows/xcodebuild.yml@v0.2.4
  #   with:
  #     codeql: true
  #     scheme: NutriSight
  #   permissions:
  #     contents: read
  #     security-events: write
  buildandtest:
    name: Build and Test
    uses: SchmiedmayerLab/.github/.github/workflows/xcodebuild.yml@v0.2.4
    with:
      scheme: NutriSight
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtest]
    uses: SchmiedmayerLab/.github/.github/workflows/coverage.yml@v0.2.4
    permissions:
      actions: read
      contents: read
    with:
      coveragereports: NutriSight.xcresult/NutriSight.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
